name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.0.0
homepage: https://flyer.chat

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.2
  firebase_auth: ^1.0.1
  meta: ^1.3.0

dependency_overrides:
  flutter_chat_types:
    git:
      url: https://github.com/alihen/flutter_chat_types.git
      ref: c307eb58bed4e1f96fda8c6156a3340c609a3027

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
